name: Build Android App
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set date as env variable
        run: echo "today-date=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set Repository name as env variable
        run: echo "repo-name=$(echo '{{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: SetUp Android JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: setUp Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android Apk
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Build Android Bundle ABB
        run: |
          cd android
          ./gradlew bundleRelease

      - name: Upload APK Release - ${{ env.repo-name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repo-name }}-${{ env.today-date }} - APK release
          path: android/app/build/outputs/apk/release/

      - name: Upload AAB Release - ${{ env.repo-name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.repo-name }}-${{ env.today-date }} - AAB release
          path: android/app/build/outputs/bundle/release/
